# Generated by Django 6.0.4 on 2026-04-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('assignee', 'Assignée à un livreur'), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée'), ('echouee', 'Échouée')], default='en_attente', max_length=15)),
                ('adresse_depart', models.TextField()),
                ('adresse_arrivee', models.TextField()),
                ('date_assignation', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('note_livreur', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
            },
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicule', models.CharField(blank=True, max_length=50)),
                ('zone_couverture', models.CharField(blank=True, max_length=200)),
                ('est_disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
