# Generated by Django 6.0.4 on 2026-04-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='livraison',
            name='numero_suivi',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
